version: "1.0"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meeting_ease
    ports:
      - "5433:5432"
    networks:
      - meetingease-network

  meetingease:
    build: .
    container_name: meetingease
    ports:
      - "8080:8080"
    networks:
      - meetingease-network
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  meetingease-network:
    driver: bridge