version: "1.0"

services:
  postgres:
    image: postgres:15.6
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meeting_ease
    ports:
      - "5432:5432"
    depends_on:
      - redis
    networks:
      - meetingease-network

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    command: ["redis-server", "--requirepass", "password"]
    volumes:
      - redis:/data
    networks:
      - meetingease-network

  meetingease:
    build: .
    container_name: meetingease
    ports:
      - "8080:8080"
    networks:
      - meetingease-network
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  redis:
    driver: local

networks:
  meetingease-network:
    driver: bridge