spring:
  application:
    name: meetingease

  liquibase:
    enabled: true
  
  datasource:
    url: jdbc:postgresql://postgres:5433/meeting_ease
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: halcyon.ruslan@gmail.com
    password: hifl fxfp brqz oavf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret:
    access: szdxcAew/l0CdtVhIpTDQSucIG8ZaIs8nl4LFuZ1QLHme13v9nTy+uCaV6/7oy0Kohi2JLaokndltIeOtThaww==
    refresh: gVxFuBqj6BkQVY1A8Hm3Jk0xcHQAwQ0gWJOLKwpXJLtojylfc3Y1l384GGnjKJx3RAF0ETKj7MVYvRok5sfjfg==