spring:
  application:
    name: meetingease

  liquibase:
    enabled: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/meeting_ease
    username: postgres
    password: password


  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret:
    access: szdxcAew/l0CdtVhIpTDQSucIG8ZaIs8nl4LFuZ1QLHme13v9nTy+uCaV6/7oy0Kohi2JLaokndltIeOtThaww==
    refresh: gVxFuBqj6BkQVY1A8Hm3Jk0xcHQAwQ0gWJOLKwpXJLtojylfc3Y1l384GGnjKJx3RAF0ETKj7MVYvRok5sfjfg==